version: '3'

services:
    ride-sharing:
        build: ./services/rideSharing
        #image: junaid894/ride-sharing
        restart: always

    communication:
        build: ./services/communication
        #image: junaid894/communication
        ports: 
            - 8081:8081
        restart: always
    
    rating:
        build: ./services/rating
        #image: junaid894/rating
        restart: always
    
    nginx:
        build: ./services/nginx
        ports: 
            - 8080:80
        depends_on: 
            - ride-sharing
            - communication
            - rating



